### PR TITLE
Fix openai module version to 0.28

### PR DESCRIPTION
**Pull request by kadogo**
Hello, thanks for your code, I didn't make it completely work yet, but I will make PR for the change that I must do to make it work.

Based on https://github.com/openai/openai-python/discussions/742#discussioncomment-7544918 it looks like openai module last version need some migration, but it's still possible to use the previous version for now.

Feel free to reject or correct a PR if needed.

Cheers

### CODE REVIEW

**Comment by atisharma** [comment]
Thank you.

**Comment by atisharma** [comment]
> I will make PR for the change that I must do to make it work.

If you like, let me know what the trouble is and I can try to facilitate.

**Comment by kadogo** [comment]
Hello @atisharma 

Thank you, for now I didn't really understand what the issue is.
I change the range for trying to have a smaller generation process because I only have a CPU so it is a little slow ^^

https://github.com/atisharma/chasm_engine/blob/main/chasm_engine/engine.hy#L153 (I had read that on Reddit)

When it looks like finish, I launch the client, it does the "spawning" thing and end with a request timed out. I didn't debug enough to know if the trouble is the server or client, and I sadly not have an OpenAI key for testing with it directly. So I was planning to dig further when I got a bit more time, but if you have ideas don't hesitate to ping me.

Have a good day

**Comment by atisharma** [comment]
You could try increasing https://github.com/atisharma/chasm/blob/9ae7a33349d0b87affbecf8098ef0779f425a870/chasm/client.hy#L12 if your generation is slow. If spawning fails, it doesn't really matter, it will just redo the room generation when it's needed. If you carry on, what happens?

For world generation, OpenAI is quite good, and won't cost more than a few dollars, so it's not bad for testing.

**Comment by kadogo** [comment]
Hello @atisharma 

Increasing the time make it work, but now I got this error just after writing my first text after description.
I can see that my koboldcpp is busy, but the AuthenticationError let me think the issue is elsewhere.

```
Engine error: RetryError(<Future at 0x7f6f05f01120 state=finished raised AuthenticationError>)
```

We can continue here, but maybe you prefer that I open a proper issue for a better following?

Have a good day.

**Comment by atisharma** [comment]
Yes, please open a separate issue. If you could copy in the relevant sections of the server config being used as well then it would help.
I'll look at upgrading the openai module too (which doesn't need tenacity).

**Comment by atisharma** [comment]
Just to add -- are you trying to use KoboldAI API? It's not compatible with OpenAI's API. Compatible choices are listed in the README.

**Pull request merged**
